### ISSUE TITLE
Way to stop from checking for new images

### ISSUE THREAD

**Issue by gcstang** [EugenMayer/docker-sync#126]
Is there currently a parameter I can pass when starting my sync so that it doesn't try to pull down newer images?  If I have everything currently working I don't want to perform an upgrade that "might" break my current setup.

Thank you for an AWESOME product!

**Comment by EugenMayer** [comment]
I would not recommend this, since on the one side, the images are updated rather rarely, but if, they are updated to be compatible to the docker-sync release. Thus when you update docker-sync, you will rather have more problems as with updating them.

You can disable the update checks setting `update_check=false` in your `~/.docker-sync-global.yml` - if you do so though, please always upgrade before you open issues here, thanks!

**Comment by gcstang** [comment]
Thank you, this is more for working offline, I can however see your point and it will be used as little as possible and most definitely updated prior to any issues raised.

**Comment by EugenMayer** [comment]
great, that sounds fair enough :)
