### ISSUE TITLE
Crystal vs Go?

### ISSUE THREAD

**Issue by stmpy** [EugenMayer/docker-sync#160]
Have you possibly looked at rewriting in [Crystal](https://crystal-lang.org/) instead of Go?

**Comment by seanmcc** [comment]
docker-sync is written in ruby. Personally, I don't think it needs a rewrite.

**Comment by stmpy** [comment]
maybe not, but there is a milestone about rewriting into go, so I thought I'd make a suggestion if it was being considered.

**Comment by EugenMayer** [comment]
@seanmcc i am not very eager to learn Crystal neither i see the same potential contributor-count in it, compared to Go. 

When we switch a language, it should have some key benefits, in go that means:
- no dependencies
- wide audience of contributors ( Go has been spreading very fast..not as last because of docker)
- docker is generally very Go focues, so it just my be convinient
- e.g. implementing docker-compose integration with Go is super easy and super robust, since there is a very good (native) go lib for that which is very well maintained

Crystal would fail on most of them, if not all, so i would, balsy statement (sorry) not consider it - that does neither say anything about the quality of Crystal or similar - its probably more about the ecosystem.

**Comment by stmpy** [comment]
👍 - thanks for the feedback
