### ISSUE TITLE
Any way to install other than using gem?

### ISSUE THREAD

**Issue by recidive** [EugenMayer/docker-sync#175]

**Comment by EugenMayer** [comment]
Well you can do it manually, somehow, but I do yet not see a sense in sense that. What is your purpose?

**Comment by recidive** [comment]
I'm not a Ruby developer so I don't want anything related to Ruby installed on my system, yet I want to use Docker for Mac. This is the purpose to have Docker anyway: you don't need to install development related tools in your local system, other than Docker itself.

**Comment by recidive** [comment]
A curl | bash install method would be awesome.

**Comment by EugenMayer** [comment]
This is a ruby project, not a shell script. It does not make sense to use such techniques and to torpedo what gems do offer - it is by all means and categories more convenient.

You can use the development way to install docker-sync, with its limitations, see the developer documentation. Other then that, the gem installation is for now the only one - and since you need ruby anyway, it makes the most sense of all alternatives, since gem support is there anyway

**Comment by recidive** [comment]
Fair enough, thanks!
