### ISSUE TITLE
Option to exclude files specified in .dockerignore file

### ISSUE THREAD

**Issue by stuyam** [EugenMayer/docker-sync#180]
It is awesome that you can use the ```sync_excludes``` option to exclude files that will sync to and from the container.

However, it would be great if there was an option for the ```.dockerignore``` file to be the file that specifies what things are ignored. We use a [dockerignore](https://docs.docker.com/engine/reference/builder/#/dockerignore-file) file for other setups that don't use docker-sync, so it would be great to include that instead of having to keep the ```.dockerignore``` and the ```sync_excludes``` in sync.

**Comment by EugenMayer** [comment]
Thank you for the feeedback!

Since the excludes are very different depending on the statistics, we would need to allow a lot of transformations to establish this kind of shared file.

I really do not see this effort being worth the feature and i see quiet some stuff to be done. 

If you do not plan to work on this yourself, i would rather not focus on this.

**Comment by EugenMayer** [comment]
closed to no movement, reopen if anybody wants to tackle this
