### ISSUE TITLE
[Discussion] shortcut command to "docker exec" with spinning up docker-compose with docker-sync

### ISSUE THREAD

**Issue by DocX** [EugenMayer/docker-sync#244]
Hi guys,

amazing work on the 0.2 version. The background mode is just so huge game changer for me.

I started playing with idea to have command that completely seamlessly execute command inside my development container - so development on docker on mac feels (almost) like development on the mac itself.

It involves starting up docker-sync and docker-compose in background (if it doesn't run yet) and docker exec the command supplied as argument to the shortcut.

I ended up with for example:
```
dex mix test
```

Look at here https://github.com/driftrock/dex

What it does is:
- Assumes that docker-compose up starts all your containers with the "application" one running something like `sleep infinity` - just to keep it live so you can then exec arbitrary processes in it
- Reads `.docker-compose-default-service` file with the service name you want to exec to using `dex ...`
- Checks if container is not running, and in that case runs `docker-sync start -d` and `docker-compose up -d`
- Runs `docker exec ...` (not `docker-compose exec` as it has 0.5s bootstrapping)

The question now is: How do you feel about it. Is it intended use of docker-sync? Can docker-sync adopt some idea from this? Also there is no way how to (without knowing internals of docker-sync) check that docker-sync is running, so I just always run `docker-sync start -d` and ignore if that fails because it is already running. Not sure if there would be better way to do it?

Thank you for any comments or ideas :)

**Comment by EugenMayer** [comment]
@DocX well actually it is good, but you can do it better :)

You can use https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync to automate processes right after container starts or when specific services come up, with or wihtout docker-compose orchestration

in any way, you never want to do https://github.com/Driftrock/dru/blob/master/dru#L19 .. since that will only tell you that the OS level is up, not the daemon. Would it be a DB and you would start fireing ql imports, you would fail. Use https://github.com/vishnubob/wait-for-it in those cases or a ruby based socket-test impelemtation, if you go the scripting way.

I do thing like "provision_dev_instance() if wait_until_db_up()" int he docker-sync scripting orchestration

does this give you an idea?
