### ISSUE TITLE
Auto-install option

### ISSUE THREAD

**Issue by michaelbaudino** [EugenMayer/docker-sync#304]
Would there be any interest for a `--auto-install` or `--assume-yes` option that would automatically install all preconditions without asking `y/N` ?

If so, I'd be happy to provide a PR for it, I just want to make sure there's an interest for it and no one is already working on this.

**Comment by EugenMayer** [comment]
Sure, but not sure how put push this through, since the questions in charge can be triggered on ever Thor tasks, since they are rather preconditions. What about using a global config variable? Less easy for starters but makes more sense in the current workflow.

Maybe we can provide a docker-sync config command later, so user can setup there global config interactively

**Comment by EugenMayer** [comment]
@michaelbaudino anything you started here?

**Comment by michaelbaudino** [comment]
Nothing fancy so far: I started working on it and just ended up refactoring `DockerSync::Preconditions::Osx` for readability (use more guard clauses, a few renames and some DRY). You can have a look at [the branch diff](https://github.com/EugenMayer/docker-sync/compare/master...michaelbaudino:add-auto_install-option?diff=split&expand=1&name=add-auto_install-option), if you want.

FYI, I plan to work on that tomorrow evening and Friday morning, let me know if there's anything I should know (or any thoughts, opinions, feedback, btw 👍 ).

**Comment by EugenMayer** [comment]
Gresat! Well i like most of the things, but some simplifications are not intended:\

1. has_brew? should be there to be used by different commands. How it is determined should be part of the tool method

2. DockerSync::Preconditions::Strategy.is_osx / DockerSync::Preconditions::Strategy.is_linux have the same reasons, the implementation can become more complex, thus leaving space for changing by abstracting it

Anything else is much more rubyish and clever thank you for the effort! 

I would not merge this one for 0.3.6 but since i will start working on #316 for 0.4.0 i would love to get your things in there ASAP so the merge does not become to ugly.

**Comment by michaelbaudino** [comment]
Gotcha 👍

**Comment by EugenMayer** [comment]
@michaelbaudino i am moving this one to 0.6.0, i hope you do not mind. I guess you just do not have enough time right now - fair enough, you have done so much for 0.5.0 already.

**Comment by EugenMayer** [comment]
@michaelbaudino are you planning to work on this any further - has been quiet about you in the past months :)

**Comment by michaelbaudino** [comment]
To be completely honest, I'm only working on MacOS only once a week now, and I'm expecting a child in June, so I don't think I can dedicate the time that this issue fully deserves and thus fulfill my promise :confused:

But if anyone wants to take over, I'd be happy to discuss the ideas and expectations I have about it :hugs:

**Comment by EugenMayer** [comment]
@michaelbaudino congratulations! Anything else is far below that priority :)

**Comment by EugenMayer** [comment]
closing this since we have no progress, reopen anytime when you want to continue working on this
