### ISSUE TITLE
Plan 0.3.6

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#329]
Anything you guys want to be in that.
@ignatiusreza since you are very active right now, anythin you want to push before i release it?

It has quiet some content already https://github.com/EugenMayer/docker-sync/issues?q=is%3Aclosed+milestone%3A0.3.6 and also a good amount of bugfixes - so we should not wait too long i guess.

**Comment by masterful** [comment]
👍 looks good to me - the only thing I've noticed on coworker's machines (I've since switched to Linux) is if Docker for Mac restarts, docker-sync will still have the active file watching process and thus think that everything's okay (refusing to start a new sync). At some point, we may need to update the daemonized section to check for the process id, as well as check whether the remote container is up... - maybe abstract that away into a "docker-sync check" or something that we can periodically call ourselves, as well as when trying to start a new sync...

I won't have time to work on any side projects for a few weeks, though - and even then, I won't be able to reliably test my changes given my platform switch. So I'm not sure how to step down from being a contributor, but feel free to make that change, should you deem necessary (sorry).

On a completely separate note, when's the last time we checked native Docker for Mac file syncing performance? I ask because the 'Edge' version has since released [volume mode flags](https://github.com/moby/moby/pull/31047) - though it's possible only [cached and consistent](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17040-ce-mac7-2017-04-06-edge) are currently available. I'm not sure when that will make it into a stable release (my hunch is that they're currently busy working on features they've announced at Dockercon, so possibly within a month there will be a stable release - it's usually within a month for Stable, and Edge versions are within a few days).

**Comment by EugenMayer** [comment]
@masterful i am using that mode and be aware, its not all about the volume shares, its more about he normal FS.

with the current d4m, not fixing ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/disk/on-flush you will have horribe performance on general FS stuff.

I think, right now, there is no hope that d4m will come close to acceptable performance right now, but probably https://github.com/EugenMayer/docker-sync/issues/316 will enable us using the pros of bold worlds.

side note @masterful: tried a swtich myself also, onto arch. I did not receive the performance gain i would have expected, i admit - though a lot old pain points Linux, which are yet not worth the switch. I am planning to do some deep benchmarking here though, until i actuallly can express in numbers, how much faster docker is under linux for developers.

**Comment by ignatiusreza** [comment]
@EugenMayer updated #310 with example.. would be great to have this included, though, given that you're considering #316, I'm also okay to leave #310 out if it doesn't fit into what you want to do in #316..

**Comment by EugenMayer** [comment]
@ignatiusreza #316 us far from complete, i need some time to get this done, it will be for sure 0.4.0 anyway. If it works, it will be a game changer.

I merged #310 since i think its uncritical for the current audience, wont break to much.

I think the community response will be not to great on 0.3.6 since ./dest usage will now be declining the start, but well, one needs 1 minute to fix that, so i hope it will go fine.

@ignatiusreza i did some boilerplate tests on my side yesterday, could you do some random ones too so at least i am not the only one having a good experience so far? Thanks for your effort!

**Comment by EugenMayer** [comment]
@ignatiusreza maybe also adjust the chanelog according your thoughts https://github.com/EugenMayer/docker-sync/wiki/5.-Changelog

**Comment by ignatiusreza** [comment]
Sure, I'll do some check later.. updated Changelog a little bit for `Linux Support`, replacing `unison` with `docker-sync`..

**Comment by EugenMayer** [comment]
released 0.3.6
