### ISSUE TITLE
--no-daemon doesn't seem to have any effect

### ISSUE THREAD

**Issue by carloct** [EugenMayer/docker-sync#339]
running `docker-sync start --no-daemon` still executes the process in background

**Comment by EugenMayer** [comment]
sorry, wrong docs, use --foreground

**Comment by carloct** [comment]
thanks for the quick answer, however if I run `docker-sync start --foreground` still executes it in background

```
(master)⚡ [1] % docker-sync start --foreground                                                     ~/Dev/sony/docker-dev
       note:  Starting in foreground mode
          ok  Starting native_osx
          ok  pitch-vol container still running, restarting unison in container
     command  docker exec pitch-vol supervisorctl restart unison
          ok  starting initial sync of pitch-vol
     success  Sync container started
     success  Watcher disabled by configuration
```

**Comment by EugenMayer** [comment]
Yes because the actually native_sync has no background process to watch right now. We could think about using docker exec <sync container> tail -f /var/log/unison.log for this purpose, but i did yet not implement it. If you think thats valuable, just open a issue for that.

Foreground has no effect for native_osx right now, since now background process is spawned ( it works only for unison/rsync)
