### ISSUE TITLE
Create a alpine image for unison

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#34]
I posted an issue on https://github.com/leighmcculloch/docker-unison/issues/14 because their image is very big.

But in fact you can perhaps simply switch to https://github.com/onnimonni/docker-unison

**Comment by onnimonni** [comment]
I was also using https://github.com/leighmcculloch/docker-unison as first and when I changed to my version I didn't need to configure anything since I preserved the same configs and it was just plug&play.

My version also allows to use any directory as data mountpoint (other than /data).

I hope it's useful.

**Comment by EugenMayer** [comment]
interesting, just to understand it: The effort is to minimize the size of the unison image, right? I am totally willing to doe that.

I will have to look into it myself, the image, what it does and what we need to do. But as far as you say, its a drop in replacement, right?

**Comment by onnimonni** [comment]
@EugenMayer Sorry I actually changed this one variable in the configs. See the **edit**.

**Comment by EugenMayer** [comment]
I see, that would not matter, just able to change that without any issues.

What i am thinking right now is, if i should actually fork your image and build it myself - jus to ensure we have docker-sync all out of one source. Do not get me wrong, i love contributions, but those images are centric - if they fail, docker-sync fails. They are part of the game and i would love to have this under one roof.

Would you mind me forking your image on dockerhub, and building it and pushing it on eugenmayer/unison - i would, no doubt, leave a comment whom to thank for that alpine image.

I just do not want to step on anybodies toes here!

We also maybe should introduce a setting in the options ( global options ) like rsync_image and unison_image so people could use there owns, if they like. The only fear i have is, that this will flood the issue queue with support requests due to broken images..

**Comment by EugenMayer** [comment]
one hint https://github.com/leighmcculloch/docker-unison/issues/14 the reason behind that is, it baseimage -> ubuntu. and that will never be as small as the alpine image used by https://github.com/leighmcculloch/docker-unison

**Comment by onnimonni** [comment]
Yeah no worries use it like you want to 👍!

**Comment by mickaelperrin** [comment]
Just got my macbook back from repair. I start working on this also, mainly to add `fsevents` on the container side also. If you're not interested by this, I would love an (undocumented / unsupported  if needed) option to specify the image to use.

**Comment by gagarine** [comment]
Very nice! Thanks.

**Comment by EugenMayer** [comment]
@onnimonni i forked to https://github.com/EugenMayer/docker-unison - i hope thats how you expected things to work out. Give me your blame if i just should change something :)

**Comment by EugenMayer** [comment]
@onnimonni i pushed the image and created a branch on https://github.com/EugenMayer/docker-sync/tree/feature/new-unison-image

when you check this branch out, then 

```
bundle install
cd example
thor sync:start
```

The unison image starts but, the files are synced initially to /app/code, but they are not "resynced" anymore. Any clues?

You should change example/data2/somefile.txt

You can check it this way
```
docker exec -i -t simpleexample-sync sh
cat /app/code/somefile.txt
```

Thanks

**Comment by EugenMayer** [comment]
implemented and part of the master now
