### ISSUE TITLE
Show better logging to determine status

### ISSUE THREAD

**Issue by greggilbert** [EugenMayer/docker-sync#353]
In 0.4.2, it's hard to tell what the status of the sync is. In 0.3.x it was echoed out as part of `docker-sync-stack start`, but that seems to have gone away. As far as I can tell, bashing into the sync container and `tail`ing /tmp/unison* shows what I'm looking for.

**Comment by EugenMayer** [comment]
Then you better read the release notes :) https://github.com/EugenMayer/docker-sync/releases/tag/0.4.2 or here https://github.com/EugenMayer/docker-sync/wiki/5.-Changelog

And it will tell you exactly what you want, and even better then it has been in 3.x :)

**Comment by greggilbert** [comment]
```
$ docker-sync-stack start --foreground
ERROR: "docker-sync-stack start" was called with arguments ["--foreground"]
Usage: "docker-sync-stack start"
```

So are you saying that the right way to do this would be to do `docker-sync start --foreground` in one tab, and then `docker-sync-stack start` in another? If so, that's not at all clear from the docs.

**Comment by EugenMayer** [comment]
There os not foreground for stack, because the compose thread is taking the lead hear and i did not implement "tee" to do so. I think, for the time being to ensure you trust / analyzed the sync and its reliability, you could do the above yes.

If you do not like to do so, you can implement it yourself by

docker exec <synccontainer> tail -f /tmp/unison

And or automate this by scaffolding it https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync

Or, if you feel you really need this, you can try to solve that in docker-sync and doing a PR - i would love that. For now, i think the current tools are O.K. to work with - but there is always ways to improve

**Comment by greggilbert** [comment]
As an alternative, would it be possible to send unison's output to stdout so you could just do `docker logs -f sync_container`? On May 5, 2017 4:50 PM, Eugen Mayer <notifications@github.com> wrote:There os not foreground for stack, because the compose thread is taking the lead hear and i did not implement "tee" to do so. I think, for the time being to ensure you trust / analyzed the sync and its reliability, you could do the above yes.
If you do not like to do so, you can implement it yourself by
docker exec  tail -f /tmp/unison
And or automate this by scaffolding it https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync
Or, if you feel you really need this, you can try to solve that in docker-sync and doing a PR - i would love that. For now, i think the current tools are O.K. to work with - but there is always ways to improve
