### ISSUE TITLE
daemon.log should be outside the project folder?

### ISSUE THREAD

**Issue by rogamoore** [EugenMayer/docker-sync#369]
I'm not 100% sure as I just updated to 0.4.2 and have to experiment a bit more, but I noticed that there is now a .docker-sync folder with a daemon.log being created.

In my opinion this should be outside the project folder otherwise I now have to do the following for every single project using docker-sync:

- add .docker-sync to .gitignore
- add .docker-sync to .dockerignore
- What about syncing? Will the folder + daemon.log be synced too as it's in the project folder?

**Comment by EugenMayer** [comment]
yes this is the case since 0.3x and we need it inside, please add it to your .gitignore

**Comment by rogamoore** [comment]
Not really helpful, because you also made the daemon mode default and you didn't answer my question about syncing - but ok - your decision.

**Comment by EugenMayer** [comment]
it would be synced if you use './' as src, which is uncommon as a project structure as is, but yet. Thus you would need to add .docker-sync to your ignores. Its possible that we do add this automatically, since it does not make sense, open an issue for that, if you like this to happen.

It has reasons why it is the project folder, see the old issue for daemon mode why it has been decided.

.dockerignore is something totally different and it has to do with build of docker images

**Comment by rogamoore** [comment]
All our projects have the docker-compose.yml & docker-sync.yml in the root of the project which happens to be Symfony projects most of the time. So of course we need to sync "./" and I don't see how this is not a common case.

Also as we use docker in production we have to build docker images, so if you don't add the log file to dockerignore you'll end up with images in the registry containing a local log file.

docker-sync is a developer tool and as such it should not write any temporary files to my project.

I'll stick with 0.3.6 then.
