### ISSUE TITLE
Getting "Please add :nocopy warning" when no dev.yml exists

### ISSUE THREAD

**Issue by mike-potter** [EugenMayer/docker-sync#372]
### Error/Feature Requestion/Docs

When running "docker-sync-stack start" I am getting the warning:
"warning  Please add :nocopy to every named-volume mount you defined in your docker-compose-dev.yml!"
However, I don't have any docker-compose-dev.yml file (and don't want one).  The volume mount in my docker-compose.yml file already has the :nocopy option.

This only started happening when I upgraded to the latest docker-sync 0.4.3.  Was using 0.4.0 before that I believe.

### Docker Driver
docker-machine + vbox

### Sync strategy
unison

### your docker-sync.yml
version: "2"
options:
  verbose: true
syncs:
  d8-osx-sync:
    sync_strategy: 'unison'
    src: '.'
    sync_prefer: 'src'

### OS
OSX 10.12.4

**Comment by mike-potter** [comment]
Ok, this is a bit more obscure.  I only got this warning the first time I ran "docker-sync-stack start" until I finally answered "Y" to it.  After that I don't get the warning any more.

Should also note that I got the warning "That means that unison is picked as a default automatically if you use docker-machine
Just wanted you to know that! (y/N)" the first time I ran it, even though "unison" is specified directly in my docker-sync.yml file.  But again, it only happened the first time I ran it.

So seems like something is wrong with the initial startup state.  If I can find a way to reproduce it I'll let you know.

But the first message should check if docker-composer-dev.yml exists, and the second message shouldn't be shown if the sync_strategy is already set to unison.

**Comment by EugenMayer** [comment]
We do not detect what is what, we just tell you. Docker-sync is not a giant auto-detect wizard :)

Neither we detect if you already have it or what you have, the user has to map it themself. Thats way to much effort to get those things up an running otherwise, way out of scope for docker-sync yet.

Thanks for the feedback

**Comment by mike-potter** [comment]
Then is there an option to skip these questions or automatically answer them?  The use-case that this is a problem for is when trying to automate via a script, esp on a CI environment where there isn't a person to answer the question.

The first issue is also very confusing to users who are not using a docker-compose-dev.yml and don't understand why they get the message.

Given the other issue regarding native-osx, just be sure to remove the 2nd message once native-osx is no longer the default again.  Again, this is very confusing to users who are not using docker-for-mac and not using native-osx and have no idea what this is talking about.

So I would hope you give more consideration to this and provide an option to disable these initial notifications.

**Comment by EugenMayer** [comment]
There will be no such option, what you require is a convenience of a product but this is just yet another open source tool.

So i rather try to get the information to the users and they decide, if it is for them or not then hiding it or even handcraft every bit customized for the environment the user is in.

I understand your feedback and also the benefit - but this just wont happen because it just blows the time for docker-sync out of every Dimension. So i am not arguing what you say makes sense and adds value, i rather be honest and tell you, that wont happen.

If you want to use it and deploy it, use proper tools like boxen or kitchenplan to predoploy the gem, put the ~/.docker-sync-global.yml in place and generate the status you have or need. I cannot see docker-sync going beyond that, sorry to say

**Comment by EugenMayer** [comment]
There will be no such option, what you require is a convenience of a product but this is just yet another open source tool.

So i rather try to get the information to the users and they decide, if it is for them or not then hiding it or even handcraft every bit customized for the environment the user is in.

I understand your feedback and also the benefit - but this just wont happen because it just blows the time for docker-sync out of every Dimension. So i am not arguing what you say makes sense and adds value, i rather be honest and tell you, that wont happen.

If you want to use it and deploy it, use proper tools like boxen or kitchenplan to predoploy the gem, put the ~/.docker-sync-global.yml in place and generate the status you have or need. I cannot see docker-sync going beyond that, sorry to say

**Comment by mike-potter** [comment]
A command line tool like this should not be asking user questions and blocking access.  It's fine to provide informational text, but you should not be stopping and waiting for a response.  I'm afraid this could be a deal-breaker for real-world use of this excellent solution, so would sad to see it not used for something simple like this.

If you are saying that a ~/.docker-sync-global.yml file could be created to prevent these questions, then just document what the contents of that file need to be and mark that as an answer to how to prevent these messages.

**Comment by EugenMayer** [comment]
docker-sync is by no means a tool for automation, i never has been designed for that.

It is a tool for a human, for a developer, to get his development stack up and running. Not for CI/CD tools to build oder OSX (why anybody would ever do that under OSX?) or any other automation.

So maybe the mission of the tool does yet not come through - but if you really use docker-sync in automation, its probably the wrong tool. 

And the opt-in, the "yes i have read it" is needed - because people frankly down read, then fail, then open an issue and then wait for help. You could tell i am pessimistic but i bet you know, i am realisticly right on that. This protects the motivation of the team working on docker-sync i guess
