### ISSUE TITLE
Refactoring Idea: Extract environment munging logic into its own namespace

### ISSUE THREAD

**Issue by ignatiusreza** [EugenMayer/docker-sync#377]
Instead of having `#is_linux?`, `#is_osx?` etc under `Preconditions`, we should move it into its own namespace, e.g. `DockerSync::Environment`..

there're 2 options from there, either we have it included into classes where checking for environment is needed via `include DockerSync::Environment`, or we just call method function like `Environment.is_linux?`.. I lean toward the later approach since it feels cleaner, but it require more typing..

thoughts @EugenMayer & @michaelbaudino ?

PS: @michaelbaudino since you're working on #337, maybe you'll be interested to work on this too? if not I'll be doing it.. asking just to avoid potential double work.. :grin: 

PS2: btw, why does the method prefixed with `#is_`? I thought in ruby, [the standard](https://github.com/bbatsov/ruby-style-guide#bool-methods-prefix) is to just have `?` suffix, e.g. `Environment.linux?`..

**Comment by michaelbaudino** [comment]
Yep, I tried to refactor this whole namespace twice, but failed twice 😕 I'll probably give it another try because it's now a personal challenge but feel free to give it a go 👍 

I'm thinking of splitting responsabilities into multiple classes/sub-namespaces:
* checking requirements/environment (stuff like `linux?`, `docker_available?`, `brew_available?`, _etc_...) that should be a singleton for memoization of immutable things (like `linux?` but unlike `docker_running?`)
* installing requirements (stuff like `install_brew`, `install_unison`, `cleanup_legacy_unox`, _etc_...) that should not be a singleton
* a wrapper (with a single public API entrypoint like `install_missing_requirements`) that would check each requirement availability and install them is missing (_e.g._ `install_unox unless unox_available?`)

What do you think?

Ho, and I totally agree with your PS2: my in-editor Rubocop is going mad with those 😄

**Comment by ignatiusreza** [comment]
Agreed on the general idea.. let's extrapolate even further and clarify the boundaries..

I see `environment` as something that either comes with the machine (like OSes stuff), or something that naturally need to be there for this project to even exists (`docker` -- why are not checking for `docker-compose` btw?).. `brew` is a bit of a gray area, though I guess we can look at it as `package_manager` on which we can potentially abstract different package manager like `apt-get`, `yum`, etc.. i'm not so sure if `install_brew` is something can automatically be done, or if it's something that our user just have to deal with..

Other requirements like `unison` or `rsync` are what I would like to call dependencies (naming of course can change), are governed by the project configuration, and should only be needed if the configuration said so.. this should also be extended into the docker images.. why should I need rsync image if I don't use rsync strategy?

I'm not so sure that memoization is the right motivation for singleton.. by definition, a class should be a singleton if there can only be one instance of it, like the global config.. environment doesn't necessarily need an instance, so I think it should be just a module with a bunch of module function.. each of these functions should be cheap enough, that having memoization might be too much..

I'm not so sure as to why on your second point, you think that it shouldn't be singleton.. care to elaborate?

**Comment by michaelbaudino** [comment]
Thanks for your ideas and thoughts @ignatiusreza, I agree that environment checking could be just a module and that we can have an abstraction layer for the package manager 👍

**Comment by EugenMayer** [comment]
i am currently putting together the laste 0.4.x release 0.4.5 with all the bugfixes, then the merge is comming. Prepare yourself @michaelbaudino  :)

**Comment by michaelbaudino** [comment]
I actually have something quite promising, I should be able to create a PR
tomorrow or Saturday.

**Comment by michaelbaudino** [comment]
I pushed a first pass of such a refactor on the `refactor-preconditions` branch: https://github.com/EugenMayer/docker-sync/compare/refactor-preconditions

I tried to follow most of what we discussed here, @ignatiusreza.

Feedback is highly welcome 🔎 

PS: I did not create a PR yet, because I need to write some tests.
