### ISSUE TITLE
[idea] Rework configuration reference to explain each option

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#39]
Instead of showing a annotated configuration, rather split into global options and syncs option and explain each value as:
- meaning
- default
- possible values / allowed values
- optional / mandatory

anybody willing to help here? Be bold https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration

everybody has write access

**Comment by thizzle** [comment]
Would a `docker-sync init` task that auto-generates a fully-documented sample `docker-sync.yml` file be useful? Similar to how `vagrant init` works.

**Comment by EugenMayer** [comment]
That Sounds like a realy good idea. Go forward doing that happy to merge such in

**Comment by henscu** [comment]
Thanks to docker-sync I've just got my Bedrock WordPress Docker Compose (V3) setup working and would be glad to add a section to the wiki for this it would help many WordPress developers.

How does updating the wiki work? I just edit it and commit?

**Comment by EugenMayer** [comment]
You Fan freely create neu Wiki Pages, just be bold!

**Comment by codycraven** [comment]
I'd really like to see a good description of each of the sync options, then breaking each configuration explanation into its own page.

This would allow the user to determine which option will be best for their use, then go access example and details strictly addresses their sync option. For example, I don't know right now if I should define _sync_host_port_ when using native_osx because the wiki mentions not using it for unison, but also that it is for rsync.

**Comment by EugenMayer** [comment]
@unnawut any chance you would pick this up. This would be so great :)

**Comment by unnawut** [comment]
Note that I haven't forgotten this issue but havn't got time to get to it yet. Will be back!

**Comment by EugenMayer** [comment]
@unnawut you have done so much already, so i am already more then happy! If you can take this on anytime, this is just over the top :)

Thanks!

**Comment by cweiske** [comment]
This can be closed.

**Comment by EugenMayer** [comment]
Right, thanks for the follow up and thank you for all the work!
