### ISSUE TITLE
Windows Support without a Posix Environment

### ISSUE THREAD

**Issue by rwilliams** [EugenMayer/docker-sync#392]
#### Why?

- Allow Windows users to user docker-sync with the minimal amount of prerequisites
- More consistent with the most common Docker for Windows workflows

#### Current Known Blockers
- Backticks [reliance on PTY module](https://github.com/xeger/backticks/issues/11) without a suitable fallback. *Backticks gem is only used for sync-stack via the docker-compose gem.
- No current strategy for handling Windows in docker-sync

#### First Steps
- Adapting the current `native osx` strategy for Windows.
- Shell out to docker-compose instead of using compose gem

**Comment by EugenMayer** [comment]
@rwilliams would consider this 0.6  or are you really going to work on this on a short-term base?

**Comment by michaelbaudino** [comment]
What about file separators? Are stuff like `require 'docker-sync/dependencies'` working on Windows? Shouldn't we be using `require File.join('docker-sync', 'dependencies')`?

**Comment by EugenMayer** [comment]
If those kind of things would be required, i would veto against this kind of implementation completely.

If we need to change our codebase to adopt windows in this particular ways i would tend to say neither it is worth the hassle, nor will the number of issues coming up _care anybody_ - it will be a one shot, 2 weeks support and then "its like it is and nobody works on the issues / user feedback" - because just the not enough people using that, which are contributing.

Please consider that to always be a long term project - and i kind of doubt it here, or at least, would say i am skeptical

**Comment by rwilliams** [comment]
@EugenMayer 0.6 is a good target. I do plan on working on this over the next few weeks but it will most likely be restricted to weekends. I personally will be using docker-sync on windows at least once a week for the forseeable future, maybe more often. Docker-sync is important to windows users because it fixes the lack of inotify support in thier containers. Rails, node, elixir/phoenix devs stuck on windows are going to rejoice.

Side note: I just realized native-win probably won't work. Does unison on linux use inotify?

**Comment by EugenMayer** [comment]
@rwilliams unison on linux uses inotify, and on OSX it uses fsevents, which is implemented by unox as an interface using macfsevents or watchdog

**Comment by rwilliams** [comment]
@EugenMayer Thanks. So a native_win strategy is out of the question as unison will never got notified of the changes in host-sync. Hello unison :)

**Comment by EugenMayer** [comment]
Closing this issue for now since i rather not expect anybody to work on this for now. If anybody though feels like he want to take on this, reopen anytime!
