### ISSUE TITLE
Feature request: Disable auto gem update check?

### ISSUE THREAD

**Issue by wulftone** [EugenMayer/docker-sync#425]
I'd like to have an option to never be asked to update the gem--it doesn't work with our workflow to do that and can add instability to our environments.  Would it be possible to add a simple config option or something to opt-in to opting-out?  Thanks!

**Comment by eggie5** [comment]
+1 this has broke my env at least twice now. More recently I'm stuck on the new native-mac sync strategy which doesn't seem to support 2-way...

**Comment by EugenMayer** [comment]
Hello, please see this discussion on why this is not available and not planned https://github.com/EugenMayer/docker-sync/issues/372 , in particular the last comment. 

We have an opt out, there will never be an opt-in for auto updates yet.
To opt out, open ~/.docker-sync-global.yml - should be self explaintory.

_*Be aware that when you opt out and then open issues which relate to older versions, i will close the issues without any further notice*_ You can disable it, but when you open new issue, be sure you upgraded to the latest version before you do so - or you issues will be closed - thanks

@eggie5 of course native_osx supports 2 way - but that is a different topic.

**Comment by wulftone** [comment]
Oh, good! This is just what I was asking for, thank you.

Any chance it could be opt-out by project instead of globally?

**Comment by donnykurnia** [comment]
@wulftone the docker-sync is a global tool, so it will not make sense to have this setting per-project because even if a particular project opt-out, but another project don't set it, the docker-sync will be upgraded anyway.

**Comment by wulftone** [comment]
I see. I've been using it exclusively with `bundle exec docker-sync-stack` which is not global--so as to not require separate projects to be updated all at once... Perhaps that's not how it's intended to be used, but it is how I like to use it.

**Comment by donnykurnia** [comment]
@wulftone I see. Well, just like @EugenMayer wrote in the #372, docker-sync is not for automated workflow, but only for development and you as the user have the freedom to decide which version and strategy that you will use. docker-sync is a gem, so it's easy to install any version that you wanted to.

**Comment by EugenMayer** [comment]
So, there is at least an effort to make the upgrade automatic: https://github.com/EugenMayer/docker-sync/issues/304 but this does not really play into this context here.

There has been a discussion if that should be done per project and we decided, it is way to hard fo the users to ensure the right scoping including way to hard to track project based configurations which are not part of a project, also the upgrade status of project A, B, C like we do globally.

Way to much effort and hardly any gain at all. The reason i say "no" to some things is, because going down that road means open a can of so many extra issues and so much complexity, that we entirely lose focus what the core issues and features of docker-sync are - which we need to have time for to let them run smoothly.

Looking at the issue queue right now, there is already some lack of time for some issues to to be tackled in time, more features wont help here :)

**Comment by wulftone** [comment]
No worries, that all makes sense. Thank you for your response!
