### ISSUE TITLE
Memory leak in unison image/container

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#43]
the docker-sync container (the last one) seem to use a lot of memory after some time:
![screen shot 2016-07-13 at 22 05 24](https://cloud.githubusercontent.com/assets/164074/16818055/0fc9e57e-4946-11e6-835c-be12797687b5.png)

Right after starting memory consumption it's pretty standard but seem to grow very quickly every time their is a sync (just add/delete a empty folder):
![screen shot 2016-07-13 at 22 11 05](https://cloud.githubusercontent.com/assets/164074/16818179/c67e53ea-4946-11e6-9f9e-8f3fbfc6a1ed.png)

**Comment by EugenMayer** [comment]
what means after some time? 3 hours? 6 hours? After a sleep?

**Comment by gagarine** [comment]
It's not after some time, but when you add/remove folder (didn't try with files yet).

To reproduce:
 - $docker-sync start
 - $docker-compose up
 - then on the sync folder on the local machine add an empty folder
 - check the memory (is gone up)
 - remove an empty folder
 - check the memory (is gone up)
 - ...

Every time you remove/add folder (didn't try with files) memory usage is growing.

**Comment by EugenMayer** [comment]
Not sure we can actually do something about this - since this is IN the container, its simply rsyncd . So if you like, search the web for it, it has nothing to with the use-case, its just what an rsync --deamon server runs. Current, we run unter jessie, the new generation rsync image will use alpine: https://github.com/EugenMayer/docker-rsyncd-image

Its yet not finished though.

It could be probably something in the settings of rysncd, currently we use https://github.com/EugenMayer/docker-rsyncd-image/blob/master/run#L20

I will not activly working on this issue, i would be glad, if you could join us here and work on those reasons. Thanks!

**Comment by gagarine** [comment]
I'm using unison not rsyncd. I should check if it do the same things we only the unison images (without docker-sync).

**Comment by EugenMayer** [comment]
@gagarine do you already use the new unison images? https://github.com/EugenMayer/docker-unison 

try a ```docker pull eugenmayer/unison``` see if he pulls anything. If yes, try to reproduce your use case. The unison configruation can be seen above

**Comment by gagarine** [comment]
Good news, the problem only append with `verbose: true`. I remove this options (than I didn't want, i just copy pasted from the doc....) and memory usage go down after the sync.

CPU/MEM can still be relatively high sometimes even with the new smaller image but their is no leak has the memory usage go down pretty quickly.

For me we can close this bug.

**Comment by EugenMayer** [comment]
CPU/mem will go down with the new image due to even-filtering

**Comment by EugenMayer** [comment]
For reference @gagarine https://github.com/EugenMayer/docker-sync/pull/46 this fix will make fswatch even more effective

**Comment by EugenMayer** [comment]
documented your findings https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration here, thank you!
