### ISSUE TITLE
Allow a prefix to be added to container names from command line

### ISSUE THREAD

**Issue by kducharm** [EugenMayer/docker-sync#439]
### Error/Feature Requestion/Docs
In trying to find a solution for #427, allowing for a prefix to be specified as a parameter to docker-sync would resolve the issue of using `docker-compose -p projectname` to have multiple sandboxes running on the same codebase by adding a similar parameter to docker-sync so that the volumes are uniquely named.

**Comment by EugenMayer** [comment]
@kducharm this will need a load of work and also, i will not add this without having a maintainer for this. This is a little door to hell since we most probably cannot do a lot of assumptions and simplifications about names and things, that said, i am sorry, very sceptical about giving this my blessing right now.

**Comment by kducharm** [comment]
Rather than trying to introduce this parameter, I was able to create a docker-sync.template.yml file and prior to running docker-sync, used a custom build script to generate the right container name using token replacement into a docker-sync.yml prior to starting everything.
