### ISSUE TITLE
Vagrant integration

### ISSUE THREAD

**Issue by hekevintran** [EugenMayer/docker-sync#469]
Using Docker with Vagrant uses Docker volumes (not sure if it uses osxfs) and performance is so bad it is unusable.  What would it take to integrate docker-sync with Vagrant or is this not worth doing considering Vagrant is just a metalanguage?

**Comment by EugenMayer** [comment]
docker-sync is about docker replacing vagrant in the first place :)

And there is literally no reason to use vagrant when you have docker beside very few exceptions like testing chef recipes include iptables configuration use test-kitchen. Anything else is just do vagrant, lets call it the old way, or use docker - combining both does just make no sense - its a layer in between which will not help you. Anything vagrant will be offering you, can be done by docker-compose. And the linux hypervisor will either be done by dockertoolbox using virtualbox or fusion, or you go with docker for mac ( i would recommend that ) and then use it with docker-syncs native_osx strategies.

dockertoolbox can be user with unison and rsync with docker-sync, but not with native_osx, since OSXFS is not used.

We could support vagrant, but we wont simply because of adding this is just adding.

---

do not get me wrong, i love vagrant for what it is, i even publish my own images there - but i use it for full virtualization requirements only, be it using packer, test-kitchen for iptables / bridge interfaces and so on.

**Comment by hekevintran** [comment]
I disagree about it not making sense to use both Vagrant and Docker.  The point of Vagrant is to be an abstraction between the virtualization technology and the development environment configuration.  Using Docker as a virtualization provider for Vagrant makes perfect sense, just as much as VirtualBox, VMWare, etc.  There is no hard association between Vagrant and full virtualization.  The point of Vagrant is that you can switch virtualization providers without changing any code.  Of course anything Vagrant does can be done by docker-compose, just like it can also be done by using VirtualBox or VMWare alone.  That is not evidence that combining them does not make sense.

Thanks for your hard work on docker-sync.  It's been really useful.  I can tell it took you probably a lot more time to get it right than you probably wanted.  It's crazy that you need this complicated 2 container OSXFS and unison and volume mounting situation just to get decent file system performance, but hey it works!

**Comment by EugenMayer** [comment]
There is no reason in having this abstraction at all with docker, docker is exactly this abstraction.

You can also put a KVM box into a vagrant, that would make about the same sense as putting a docker container into vagrant.

Really the only reason to put docker container in a HV VM is basically strict security encapsulation, because that is something docker yet not properly/entirely handle. So you have VM1 with docker-stack1 and VM2 with docker-stack2. If stack1 gets hacked, it cannot escalate to to stack2 even if the docker container leaks to the Host ( the VM1 ).

Since that is obviously nothing you need / want in development, nobody would do this.

E.g. everybody on linux who runs vagrant and in there a docker-engine just to run containers would be at least going to answer some confused questions when others see that.

Sure, OSX is different, since this crappy kernel is not supported by the docker-engine, thus you will need a HV anyway. Still, adding a HV like vb/fusion has its downside since network stack is not shared, exposed docker ports are not available on localhost. While this sounds like a silly detail, it is absolutely not.

Try the different setups for debugging XDEBUG with vb/fusion against hyperkit (docker for mac) and you will see a huge practical difference.

Try to include database-binding in intelli-j ide and share it with out team when its not localhost:3306 but rahter "some.random.local.network:3306". 

Try running a consul client with default configuration ( localhost 8500 ) and a lot more services, which will work very convinient with localhost:port, but are much more inconvenient to configure  with someip:port.

So, i guess we have to agree to disagree here :) Thats not bad either, i am sure you are happy with what you have too.

Thanks for the heads up, yes it was not a straight shooter - and yes its silly and PITA to even ever have the need to create docker-sync in the first place. The whole project should be absolute ASAP.

**Comment by hekevintran** [comment]
I think we have a misunderstanding.  I am not talking about running Docker insider VirtualBox through Vagrant.  I am talking about using Docker for Mac through Vagrant in place of VirtualBox through Vagrant.  I agree it makes little sense to run VirtualBox just to run a Docker container inside it except that before Docker for Mac this was the only way to do it.  You answer seems to assume that using Vagrant implies a hard association to a full virtualization provider which is not true.
