### ISSUE TITLE
Operating System name in lates Docker 4 Mac is changed

### ISSUE THREAD

**Issue by donnykurnia** [EugenMayer/docker-sync#477]
!!!! Important hint !!!!!

> Please do not create issues for [docker](https://docs.docker.com/) or [docker-compose](https://docs.docker.com/compose/reference) related questions. Ensure you understand the tools properly and consult their documentation first. Please understand what [docker volumes](https://docs.docker.com/engine/admin/volumes/volumes/) / [docker-compose volumes](https://docs.docker.com/compose/compose-file/compose-file-v2/#specifying-byte-values)

> Please be sure to have a look at our [documentation](https://github.com/EugenMayer/docker-sync/wiki) too, especially [configuration](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration) and our starting point the [boilerplate](https://github.com/EugenMayer/docker-sync-boilerplate)

### Error/Feature Requestion/Docs
Error

### Docker Driver
d4m
Version 17.10.0-ce-mac36 (19824)
Channel: edge
a7c7e01149

### Sync strategy
need to set `native_osx` explicitly in `docker-sync.yml`

### OS
OSX Version 10.12.6

Related code:
https://github.com/EugenMayer/docker-sync/blob/d1974b61ad55d87a72bcebcb245759d116ebee39/lib/docker-sync/dependencies/docker_driver.rb#L9

In the new D4M:
```
$ docker info|grep Operating
Operating System: Docker for Mac
```

**Comment by tripox** [comment]
Here's a fix: #478

**Comment by EugenMayer** [comment]
@tripox great catch! could you please rebase the PR and also run the tests https://github.com/EugenMayer/docker-sync/wiki/3.-Tests#automated-integration-tests using the master (broken) and then on your branch ?

I cannot run the tests myself on HS since i have Sierra only.Thanks!

**Comment by greggilbert** [comment]
@EugenMayer: I know you've been storing up releases to get ready for 0.5, but I think this should be added to the latest 'stable' and tagged (0.4.7, probably). The directions on the docker-sync homepage say to install 0.4.6, which is several months out of date with master.

For reference to others, my team has had success by using the latest version of the `master` branch:

```
$ gem install specific_install
$ gem specific_install EugenMayer/docker-sync
```

**Comment by EugenMayer** [comment]
@greggilbert i am not really following here. We are talking about d4m edge, not the stable version. so if people like to run the experimental stuff which is probably even still going to change, thats fine. But it should be no suprise that things going to break, you have to compile / pull other packages from source since they are not compatible.

0.4.6 is several months old, but it does not really have any critical issues right now - that said, i slowed down the release cycles since people complained its way to rough ride, to fast paced, to buggy. 

So the reaction was the slow down, test more and plan it bit more far ahead since docker-sync is used quiet a lot nowdays ( we have 30.000 downloads on rubygem for the current release only - so we might have a active userbase of 5.000-10.000 people or even more. I do not want to turn the upgrade into a nightmare, so 0.5.0 will be the next and also well planed ahead. Hope you can agree here

**Comment by danquah** [comment]
@EugenMayer do you have a rough target-date for 5.0? With their current release-cycle we can probably expect the next d4m stable to be release at the end of the year, so I guess thats the ultimative deadline for getting this fixed?

**Comment by EugenMayer** [comment]
yes for sure, i actually plan to have 0.5.0 out in the next 2 weeks if nothing disruptive happens. So we should be save to go.

I will publish 0.5.0-beta1 this week, so you can all have a jump on that, having some reports / issues before we go for the RC1 - what do you think?

**Comment by danquah** [comment]
Will be happy to test it out!

**Comment by EugenMayer** [comment]
[0.5.0-beta1 is out]( https://twitter.com/DockerSync/status/925296393689985024 ) - please help testing!
