### ISSUE TITLE
Is there a way to sync a single file instead of the whole folder

### ISSUE THREAD

**Issue by markremedio8** [EugenMayer/docker-sync#500]
Is there a way to sync a single file instead of the whole folder?

I have this feature that only the binary file needs to be sync excluding all the other files in a directory. Is it possible with docker-sync?

**Comment by codycraven** [comment]
@markremedio8 it would be far more efficient to use a regular docker bind mount rather than docker-sync.

Docker-sync is most useful to projects with many sync'd files in them which encounters performance woes with docker's bind mount. I don't recall ever hearing docker-sync being used in a single file sync situation.

**Comment by EugenMayer** [comment]
There is nothing more to add, beside what codycraven said, its not possible
