### ISSUE TITLE
docker-sync-stack start to pass options to docker-compose up

### ISSUE THREAD

**Issue by cjlarose** [EugenMayer/docker-sync#502]
### Feature request

It would be very nice to be able to execute

```
docker-sync-stack start --build --abort-on-container-exit
```

and have that command start docker-sync in the foreground as normal and also start the equivalent of 

```
docker-compose up --build --abort-on-container-exit
```

**Comment by EugenMayer** [comment]
Right now, we need to close that FR due to "cannot fix" since we use a docker-compose wrapper gem instead of the cli.

But replacing the gem is in the planing, then features like this could and should be possible.

I am closing this FR, but i am fully aware that this would be very useful ( there is just no good way to do that right now )
