### ISSUE TITLE
docker exec -> bash script permissions : unknown 

### ISSUE THREAD

**Issue by raupie** [EugenMayer/docker-sync#512]
### Error/Feature Requestion/Docs
root@****-pc:/d/Sandbox/dockersync# docker exec webserver /var/www/html/test.bash
OCI runtime exec failed: exec failed: container_linux.go:295: starting container process caused "exec: \"/var/www/html/test.bash\": permission denied": unknown

### Docker Driver
Docker 17.09.0

### Sync strategy
unison

### your docker-sync.yml
version: "2"

options:
  verbose: true
syncs:
  app-unison-sync:
    sync_args: ['-perms=0']
    sync_strategy: 'unison'
    sync_host_ip: '127.0.0.1'
    sync_userid: 33
    sync_excludes: ['.gitignore', '.idea/*','.git/*','*.log']
    src: './'

### OS
Windows 10 (1709) WSL 

####
So big thank you, docker-sync has solved all my I/O issues with a larger symfony project I am working on. However I am trying to solve this very last piece of the puzzle with getting local development environments to work with Windows environments using WSL + Docker + Docker-Sync.

Before docker-sync, the volumes would share my files and the permissions would be set for 755 and were owned by the root user so I could run docker exec webserver /var/www/html/install.bash which would install composer etc. However with docker-sync + unison I am seeing the permissions are set for 644 and I am no longer able to run my custom bash files. I would work around this by setting my bash file permissions in the entrypoint.sh in my dockerfiles, however these bash scripts are created on the fly through another application and then cleaned up after they are complete. I.E. running mysql import/export bash files. 

Is there a way to modify the sync permissions so allow for files to be executed via docker exec? 

Thank you.

**Comment by EugenMayer** [comment]
Thank you for the heads up!

i cannot really help you with that, but there are some places you might look at. 

 - does unison provide a method to set the umask? If yes, use the sync_args to set it
 - check if the folder applies umasks or something in the fstab enforcing it

There is nothing in docker-sync doing a chmod at all, so that is either something by unison ( i very very much doubt that ) or much more likely a system setting (fstab/sticky bits/umask) - which have not been applied when mounting with OSXFS directly, since that local binds something on top, those rules then do not apply.

Other then that, i will not able to help you, sorry. Not using windows for those kind of things, no way those very specific issues can be tackled by me.

**Comment by raupie** [comment]
Thanks for your suggestions. I'm trying to follow them but struggling. 

Is there a way unison can change the mode? Would be nice to set the sync to create the files with the +x perm.

**Comment by EugenMayer** [comment]
http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html

**Comment by raupie** [comment]
so there is a big difference when trying to run a bash script via exec. 

docker exec _container_ /var/www/html/script.bash vs docker exec _container_ bash /var/www/html/script.bash

I was missing the bash keyword and immediately my script executed.
