### ISSUE TITLE
Improve Update Logic To Allow Unattended Or Ignoring Updates

### ISSUE THREAD

**Issue by mwreppa** [EugenMayer/docker-sync#559]
We are using docker-sync for deploying test servers of branches within our projects using Jenkins CI. Unfortunately, as soon as 'docker-sync start' is called there will be a check for updates which is blocking until the update is accepted or ignored:

> warning  There is an update (0.5.6) available (current version 0.5.3). Please update before you continue
> Shall I update docker-sync to 0.5.6 for you?

After updating nothing happens and you have to call 'docker-sync start' again. This causes our builds to fail as soon as a docker-sync update is ready.

This also happens on running 'docker-sync start' with an up-to-date version but with unison being outdated:

> warning  There has been a major unison update. Please clean and restart all your stacks. If you are using the unison strategy, please upgrade unison by doing 'brew update && brew upgrade unison' to upgrade to 2.51.2
> Just wanted you to know that! (y/N)

If answering with 'y' the following prompt is blocking again:

>warning  If you are upgrading from 0.5.4 or below, please run `brew update && brew upgrade unison` AND `docker-compose down && docker-sync clean` or `docker-sync-stack clean` since you need to recreate the sync container
> Sync will fail otherwise. Continue? (y/N) 

These are all perfectly fine features and reminders if you are actively running docker-sync. But in cases where it should just run unattended like on Jenkins CI it leads to failing builds.

We would love/suggest the following considerations:

- If updates are non-breaking, provide a option which automatically answers 'y' in any update case so that the updates are being done and docker-sync behaves as usual, when there are no updates ready (this is hard for unison since it installed manually out of the docker-sync scope)

or

- If updates are breaking, provide a option which ignores updates or answers the requests with 'N' so that the docker-sync and its depending binaries are used as they are, disregarding any updates

The second option seems to make more sense in a context like Jenkins CI since you want to achieve reproducible builds.

It would be nice if this could be considered for further docker-sync releases. We really appreciate this piece of software and are thankful and glad that you guys are working on it. Thank you very much!

**Comment by EugenMayer** [comment]
## Unattended
Sorry, we will not support unattended since docker-sync is no made for CI usage and can very simply be avoided in all CI environments by simpley using `docker cp` - so working on unattended will be a noop for sure from my side. If you like to invest time in here and can provide a rather simple fix for this, i would consider merging that one in.

If you really want to use it in CI environments, just ensure you do the following:
regularly run

```
gem update docker-sync
## update ~/.docker-sync-global.yml  .. field upgrade_status: 0.5.6 to the latest installed version
```

## Stop updates
There is a way for this already, i just not really document this "very publicly" since too many people will then do exactly that and then just fill up the issue queue with issues were the answer is "fixed already, please upgrade"
just see your ~/.docker-sync-global.yml i think anything else should be self explanatory :)

Thank you for the heads up!

**Comment by mwreppa** [comment]
Thanks, i will have a look at that!
