### ISSUE TITLE
Introduction of NFS strategy

### ISSUE THREAD

**Issue by adiq** [EugenMayer/docker-sync#576]
### Feature Request

As of Docker for Mac 18.03.0-ce-mac59, native NFS volume sharing was introduced.
Addition of NFS sync strategy should be considered as the users still report problems with inotify events problem. 

There already popped up some [guides](https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc) and [tools](https://github.com/MDobak/docker-symfony) in this regard.

The question is how fast it is compared to other strategies in real projects and if it's worth implementing. I welcome everyone to the discussion 😃 

### Docker Driver
Docker for Mac

**Comment by EugenMayer** [comment]
well we made some tests already: https://github.com/EugenMayer/docker-sync/wiki/Alternatives-to-docker-sync#nfs

Usually NFS should be about 3 times slower in the runtime then native speed. Its not something i would directly considered, but its not bad either - it can be a reasonable tradeoff for some.

But right now i am not planning to work on an NFS strategy - what about you? Are you interested in creating a PR? :)

**Comment by rodrigoaguilera** [comment]
Maybe instead of native_osx a native_nfs strategy can be considered that still uses a unison container and benefits from the performance while not missing inotify events (hopefully nfs does not suffer from this problem).

Having said this I don't have the time to implement it. First thing will have to be consider how to ensure the user has configured the nfs server on the mac properly.

**Comment by EugenMayer** [comment]
That can be done @rodrigoaguilera - exact the way you mentioned it and yes the container would have native speed then. 

The question is, what do we need on OSX to have a nfs server in the first place? Its seems like you still start an NFS server yourself - what is the actual "integration" in d4m at all?

**Comment by rodrigoaguilera** [comment]
I think before the nfs "integration" in d4m the required nfs modules/packages for the linux kernel were missing. I remember reading guides on how to install them inside the VM.

Even that "integration" can be ignored by doing the nfs mount inside the docker-sync unison container and not the VM. Maybe this saves the users some painful configuration inside docker-compose.yml.

I feel the guide is not very clear when it uses environment variables. I have never seen a reference to an env var like #{CONTAINER_DIR} with a '#' instead of "$"

**Comment by EugenMayer** [comment]
that still leaves us with the issues of running a NFS server or client on osx, which at least for the former one needs admin permissions du to the privileged port.

the cool thing with docker-sync nfs2unison compared to the other NFS solutions is, that we ca fix the uid mapping issue fairly easy.

**Comment by EugenMayer** [comment]
closing this due to lack of commitment by all of us I guess :)
