### ISSUE TITLE
Feature request: Enable passing of additional options to the docker-compose file

### ISSUE THREAD

**Issue by kunalbhagawati** [EugenMayer/docker-sync#620]
### Feature Requestion
As of now, docker-compose file version 3.x has some incompatibilities with 2.x that it addresses with the `--compatibility` flag.  
(https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-mode)

It would be great if we can pass it on to the internal `docker-compose` call.
Since this is a generic option unrelated to *docker-sync*, maybe we can permit passing all these parameters to the compose command?

We can use the existing `options` subsection to allow specifying this in the config file as well.

E.g

```yml
# docker-sync.yml

options:
  arguments: ['--compatibility',  ..]  # same format as the docker-engine for running commands

```

and on calling the sync command:
`docker-sync-stack start --compatibility  # and other arguments to be passed here`

**Comment by EugenMayer** [comment]
You cannot use docker-compose v3 with docker sync, see my answer here https://stackoverflow.com/questions/44720283/equivalent-of-volumes-from-in-docker-compose-v3/44744861#44744861

Beside that, that is more complicated since we currently wrap docker-compose using the docker-compose gem https://rubygems.org/gems/docker-compose

We planned to remove this gem and to use dc on the cli directly, which would make such things possible as you desire, but nobody have ever put any work into that actually - and i think it would be quite some work, not very sure though.

So if you do not plan to work on this issue for 10-20 hours yourself (just an estimation) i would rather consider closing it (i will not work on this myself)

**Comment by EugenMayer** [comment]
closing since there seem to be no interest in contributing. sorry i do not find the time to work on such FR's right now - consider reopening if anybody is interested working on this
