### ISSUE TITLE
Update docker-sync.io regarding Windows support

### ISSUE THREAD

**Issue by elieux** [EugenMayer/docker-sync#631]
Given #609, it might be useful for newcomers to mention that Windows is not really supported at the moment on docker-sync.io, rather than claiming it is.

**Comment by elieux** [comment]
I couldn't find a repo for the website BTW, that's why I'm filing an issue in this one.

**Comment by boris-brtan** [comment]
it is also Linux that is not supported, but you can use [hotfix](https://github.com/EugenMayer/docker-sync/pull/630/files) and compile  master version as 0.5.10 for yourself using that shell script that is inside the repo.

**Comment by EugenMayer** [comment]
I added the hotfix for now - thank you both. @elieux your point is valid, the issue is just that nobody has the time to really tackle that issue. I used that hotfix to get the roadblock out of the way at least and align with the statement we have on the page. i think thats the long hanging fruit for now
