### ISSUE TITLE
Handling for auto-update if sudo is needed

### ISSUE THREAD

**Issue by marek-obuchowicz** [EugenMayer/docker-sync#652]
# Feature Request
OS: OSX, all versions

## Current status
Auto-upgrade may fail, if docker-sync is executed as user on Mac OS X, as it might require root privileges for `gem update (...)` command

## Better solution
Add commandline option OR configfile entry OR env variable, which will enable `sudo` (so that the called command will be: `sudo gem update (...)`

## Perfect solution
Add mechanism to detect, if `sudo` is needed for auto-upgrade (not sure at the moment how it could be implemented, so even the manual "better solution" would do the trick)

**Comment by EugenMayer** [comment]
Simply do never install docker-sync in the system ruby - that is just not a really good idea by design.

Keep the system ruby untouched or you can get into just too many troubles anyway. Using `brew install ruby` you solve the issue of polluting your system and also get rid of the need of sudo for such operations.

Since i heavily discourage using system-ruby / root privileges during docker-sync, i really would just say "no no" to this feature request. I understand, different cases, different needs - but i just do not want to open this particular gate.

I am sorry, i would even hardly consider merging a PR for this feature, even if you do all the work ;/
I hope you can understand my arguments and POV

**Comment by michalkleiner** [comment]
Also you don't always install docker-sync via brew. We use macports. I think I needed sudo as well and it failed silently.

**Comment by marek-obuchowicz** [comment]
@EugenMayer thanks for your response. If those are your assumptions, then I understand and have to live with that.

I just checked why our developers installed it using system ruby. It seems they have followed actual documentation. On http://docker-sync.io/ we see the command: `gem install docker-sync`.
The page "Installation, in OS X section" only mentions installing additional dependencies (like unison or sync) via homebrew.

Eugene, for consistency, please consider either:
 - updating documentation with your approach (don't use system ruby on mac, install via homebrew)
or
 - "opening the door" for other installation methods (like with system ruby or macports) which depend on sudo

Thanks for your help!

**Comment by EugenMayer** [comment]
Not using the system-ruby under OSX is i would assume common sense.

Nevertheless, feel free to actually PR the changes on the documentation to guide the people away from it, if you think that is reasonable to mention. I happy to merge those adjustments.

Thanks!

**Comment by marek-obuchowicz** [comment]
@EugenMayer sure, will do, happy to help.

Regarding `Not using the system-ruby under OSX is i would assume common sense`:
 - that's true for anyone developing in ruby. In our project, team works with php/js and usually no one changes default system ruby, as they just don't use it
 - I personally do some ruby projects and yes indeed, i use `rvm` and I agree with you

Should I create a PR recommending using `rvm`?

Would you mind if I invest some more time and try to make docker-sync actually compatible with system ruby on OS X? By chance I have a new mac next to me, where I didn't install anything yet, so I can try to run it on default system environment and see if it could run or if we need any adjustments. That would make setup instructions easier for non-ruby developers.

**Comment by EugenMayer** [comment]
@marek-obuchowicz please do not make docker-sync sudo compatible ( rather system-ruby compatible ) - i really do not want this right now due to the reasons above. I am thankful that you offer your time here, but this is just one of those features i would turn down - sorry!

Please update the docs and use the term "user based ruby" / "system based ruby", and link the usual ways on how to use a "user based ruby". I would really name them all 3: rvm, rbenv, chruby since we do not need to be opinionated here - whatever people use / works for them ( and however they install it, be it brew/macports/manual ).

**Sidenote:** We do no ruby development in our company, ruby is for devops / tooling only, such as docker-sync. Nevertheless every person in our company gets an OSX with a user-based ruby (we are using ansible to configure our macs similar to GPO things ). I would say using user-ruby is more a "administration reason" to keep the core-system sane, lesser a developer reasons to be able to "switch ruby versions" ( which is a good reason for devs of course ).

Thanks for your work!
