### ISSUE TITLE
[documentation] Add sponsorship information to readme

### ISSUE THREAD

**Issue by syther101** [EugenMayer/docker-sync#667]
### Docs
After just discovering that this project has a patreon how do you feel about adding some kind of information about how to support the project in the readme.

While I'm happy for Github to have implemented sponsorships. The UI pop-up isn't very clear. I got confused clicking through to the `Apply to the beta` link. Which leads you to joining the waiting list.

<img width="446" alt="Screenshot 2019-07-16 at 22 11 40" src="https://user-images.githubusercontent.com/1341001/61331296-95a86280-a819-11e9-87ee-190ea9ef9ce7.png">

Maybe just a subtle bulletpoint with a link under the existing:
> - Help [here](https://github.com/EugenMayer/docker-sync/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20%20label%3A%22documentation%22%20) with the docs no matter what skill set you have

Thinking about other repos you also have badges:
https://github.com/kalessil/phpinspectionsea
https://github.com/endel/shieldsio-patreon

Love to put together a PR if you agree with adding something to the docs. I'm sure those in the community who can, would love to help support where possible.

**Comment by EugenMayer** [comment]
Well i feel a lot better if someone would offer that as a PR indeed - just does not feel right to brag arround. This all this is joined effored / community based project, a lot of people help and a lot of effort has been put by a lot of people into this lovely tool.

So if you think it would be one valid way to ask for support for the project, i am in. In any way, thanks for the heads up!

**Comment by syther101** [comment]
Agreed, I understand not wanting to brag. But open source is so important and if somebody can comfortable afford to help support a project they use regularly thats great! You and others have spent considerable time effort on this project. I'm very thankful.

It can hopefully go a little way to keeping projects like this going. Please don't feel obliged to this project either. I personally totally understand I'm not owed anything due to a contribution. I'd hope the rest of the community would feel the same.

But I understand some other OSS contributors have some interesting views of the donation support model. Frank de Jonge the author of the flysystem package for example:

https://twitter.com/frankdejonge/status/1119937555645046784
https://twitter.com/frankdejonge/status/1119947631726350336
https://twitter.com/frankdejonge/status/1148699755977084928 

If you ever feel similar to Frank. That's fine too. But otherwise I'd say shout about it 😁 . I'm sure more of the community would love to help out 👍

**Comment by EugenMayer** [comment]
Well i`am must admit, i am fine about that and since the years, i might have grown a much thicker skin. In addition i must say, i also learned to understand the "haters" and "people demanding wihtout giving back" since i personally saw a pattern of myself with a similar attitude in other projects. That whole reflection acutally helped my side understanding why people do that ( they are not always asholes just like that ) and also helped me to reduce ( hopefully eliminate ) that behavior of myself.

So i understand what frank is going to, sounds like the old python lead who stepped down and a lot more of such stories.

right now i try to limit that kind of frustration by 
a) not starting too many projects
b) work on projects i just most myself first
c) put in the "feature stop" bar early enough so i can still maintain for a longer period - instead of wasting to much energy into features in the first place (LTS before features)
d) Try to involve people for features and their maintenance or cut the features out again
e) Having people involved gives more passion back / helps removing the frustration as every cent one could get by patreon. Be it code, documentation, support, help in the tickets and so on. 

Talking about e) which is related to this, those usually fall to sleep after a while, people e.g. start using docker-sync, involve, help and the establish and just use it - and are gone (to other projects / issues in their stack ). This is where patreon can help to fill some gaps.

E.g. for docker-sync b) will be a struggle since we moved on from MacOS to Linux for development - that said, all the other points will need to keep the steam up for me to support as much as i can - or cannot.

So everybody please feel invited to participate in any manner first and if you cannot but still like to do so, patreon might be a thing helping.

@syther101 thank you for actually bringin up this sensible topic. Myself, i have never took any flatter/patreon/ or alike for my OSS work - just because i do what i need and when others can use that, that's just fine.

Of course, bootstrapping a project with enough docs, generics and configuration so it can be used outside your own usecase does always take quiet some effort - but it is usually worth it :)

**Comment by syther101** [comment]
Definitely a good reflection and mentality to have. I've never been a maintainer of an open source project so its hard for me to know exactly what it would feel like. That's why I wanted to check with you first also and also open discussion for anybody else in the docker-sync community.

It too sounds like you've decided some good limits for yourself. I like the idea of LTS before fancy features. I'll have to think back to this list if I ever got fully involved with a project haha. (e) is very important too, projects with open friendly communities are the best. Always be friendly and encourage others 😄 

With regards to docker-sync and linux. I saw you mention this on Twitter and wondered what that might mean for the project. I'd be interested in why you switched and how that is going so far? Do you still use MacOS on any machines?

I personally don't have much reason to use MacOS besides the use of Sketch for design work. Switching to linux is tempting at times I must say.

As somebody who uses MacOS currently. I'll try and help out a bit more where I can. I'm not proficient in Ruby but I could certainly help with documentation and other project management type tasks 👍 

@EugenMayer In the meantime I'll create the pull request these patreon support details :)

**Comment by EugenMayer** [comment]
@syther101 thank you :)

> With regards to docker-sync and linux. I saw you mention this on Twitter and wondered what that might mean for the project. I'd be interested in why you switched and how that is going so far? Do you still use MacOS on any machines?

For any non developer work i currently plan to still use MacOS, so anything private on things like that. Right now i did not boot my OSX on any device for about 3 weeks, being 4 weeks into the linux migration.

I think for docker-sync this means, i wont run into bugs as early as must, regarding to bugs on OSX. But currently, i am always 1-2 majors behind the current stable release - so that is not the case anyway.

I do plan to support docker-sync still, for MacOS and maybe also for linux - but for the latter i simply do not even use it at all, i cannot see much sense beside "having one workflow for mac / linux / windows".

So docker-sync will be still my main project for now, eventhough i do not plan to add any fancy features for now. My next feature to work on would be utilizing monit to monitor broken unison states in the native strategy and trying to self-heal it by restarts and so on. Anything else will be just keeping it all in working state :)

**Comment by syther101** [comment]
Very interesting to hear @EugenMayer. Glad you're getting on with Linux! I don't think I would have booted my Mac either. Tinkering with all the new stuff while migrating over 😁

Sounds like a sensible plan for future work on the project too!

I guess all projects will almost always have a mix of Mac and Linux devs. I guess this is the where the docker-sync project helps most. Keeping everything simple for all developers involved. No matter what OS they use :)

Anyway, I've started work on adding the new Sponsors section to the README. I've also jazzed up the how to contribute section somewhat. It's not totally finished yet. I want to add some more effort to the contributors section and maybe add a section which describes how docker-sync tries to solve the syncing issues from an abstract perspective so anybody new can understand what is going on.

I'd be interested if you like the direction I've taken it. Please let me know what you do or don't like. The last thing I want to do here is make a bunch of changes you don't like or want 🙂

https://github.com/syther101/docker-sync/blob/syther101-readme-update/README.md

My focus was that I remember being a bit confused as to exactly why Docker was so slow when I first started using it. I did not fully understand the reasoning why either. I also wasn't fully sure what docker-sync did differently to solve the problem. Granted this was many years ago now when I started using Docker for the first time. But I thought it might be important for anybody discovering Docker on macOS or Windows for the first time 😄 

Cheers and have a good weekend!

**Comment by EugenMayer** [comment]
Wow actually your introduction what and why nails it so much. It is a very good mix of tech terms and explainotory and it just hits the right topics - this is really great. I would consider upgrading the hope with that too!

Incredible important work, thank you so much!

**Comment by EugenMayer** [comment]
@syther101 any chance you can finish you work on this one - i guess you moved on with other tasks?

**Comment by syther101** [comment]
@EugenMayer Apologise for being so slow on this. With the way the world is at the moment I do have some extra time on my hands. I'll see to getting this sorted over the weekend :) 

Hope you are keeping well!
