### ISSUE TITLE
How is it different from docker built in cached strategy?

### ISSUE THREAD

**Issue by phuongnd08** [EugenMayer/docker-sync#675]
Sorry for being naive, but how is this different from docker [cached](https://docs.docker.com/docker-for-mac/osxfs-caching/) strategy? Shouldn't docker give the container a cached version of the host that it will update belatedly?

**Comment by EugenMayer** [comment]
https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/288

Benchmark it yourself: https://docker-sync.readthedocs.io/en/latest/miscellaneous/performance.html

Since you do not trust the project statements the only way to be sure for you is to run your own benchmarks. 

Then also see https://docker-sync.readthedocs.io/en/latest/advanced/how-it-works.html
