### ISSUE TITLE
Support `sync_includes`

### ISSUE THREAD

**Issue by stevebaxter** [EugenMayer/docker-sync#680]
### Error/Feature Requestion/Docs
Feature Request

### Docker Driver
Any

### Sync strategy
Any

### OS
macOS 10.13.6

We have a complex, legacy cross-platform source hierarchy with code for Mac, Windows and Emscripten. We want to dockerise the Emscripten build, but it's very slow, hence docker-sync.

Our problem is that if we exclude folders using `sync_excludes` we would have hundreds of entries. It would also require constant maintenance, as every time someone adds a new folder that isn't relevant to the Emscripten code we would want to exclude it. 

Would it be possible to add a `sync _includes` property that controls what is included in `src`. `sync_excludes` should still be honoured (so we should include all files that match `sync _includes` and that don't match `sync_excludes`).

**Comment by EugenMayer** [comment]
Well, we simply cannot implement that, since Unison does not support such a thing - and we are bound by those limits.

The issue with project structures of big / legacy / non adjusted projects and docker sync ( actually much more OSXFS ) is a huge issue and only solveable by one single thing - restructure the project by all costs - or change to Linux. 

I am serious, right now, there is no other way. Neither excludes work as supposed on all levels, neither includes would fix it.

**Comment by stevebaxter** [comment]
That is a shame - restructuring a 30 year old project just isn't something we can do overnight. I'll raise a feature request on Unison.
