### ISSUE TITLE
vmmem.exe High CPU usage about 50% with freezing docker

### ISSUE THREAD

**Issue by gmatkowski** [EugenMayer/docker-sync#681]
### Error/Feature Requestion/Docs
vmmem.exe High CPU usage about 50% with freezing docker

### Docker Driver
Docker for Windows (Desktop)

### Sync strategy
unison

### your docker-sync.yml
version: "2"

options:
verbose: false
syncs:
applications-docker-sync: # name of the intermediary sync volume
compose-dev-file-path: 'docker-compose.sync.yml' # docker-compose override file

src: '${APP_CODE_PATH_HOST}' # host source directory
sync_userid: 1000 # giving permissions to www-data user (as defined in nginx and php-fpm Dockerfiles)
sync_strategy: '${DOCKER_SYNC_STRATEGY}' # for osx use 'native_osx', for windows use 'unison'
sync_excludes_type: 'Name'
sync_excludes: ['laradock', '.git', '.idea', 'node_modules'] # ignored directories
sync_args: ['-perms=0'] #required for two way sync ie generators, etc

### OS
Windows 10

This issue occurs randomly, usually after heavy usage, vmmem.exe process rise to 40-50% and hangs docker. To fix I need to restart docker but after few minutes problems comes back again.

It's related with Docker sync since this doesn't happen when docker-sync is disabled.

I can't even debug this because docker is stuck, so there is no way to see processes inside containers.

**Comment by EugenMayer** [comment]
That is, as under OSX, and issue with docker for windows - the file system events get stuck and / or unison blows up in the docker container of docker-sync due to the amount of file system events. so it's either of that layers, both related to the amount of FS events and on both sides we cannot do anything about it beside:

 - limit the amount of file system changes at once
 - stop the stack before you change branches for example or run `npm install` and so on
 - do not use Docker under non Linux

Right now, there is no other way to fix this, this is entirey filesystem / kernel based.
