### ISSUE TITLE
project_root: config_path should be default

### ISSUE THREAD

**Issue by ostrolucky** [EugenMayer/docker-sync#741]
Following is an config option this issue is talking about: https://github.com/EugenMayer/docker-sync/blob/0550582162ac378f836db09408c45b797d48281e/docs/getting-started/configuration.rst#L59-L60

Having it `pwd` results in confusion (see https://github.com/EugenMayer/docker-sync/issues/729) and inconsistent behaviour from docker-compose.

I would like to propose making `config_path` default, so docker-sync finds config from subfolders by default.

**Comment by EugenMayer** [comment]
There has been yet a single request to change this default - and this one is from you. This means, until we do not get more steam behind this and more people complain about this, i will strongly try to keep the deployed default as is.

docker-sync is not docker-compose, nor is it docker or anything else. It does neither propose this nor tries it to be feature complete or somewhat wrapping all this things up.

Those are 2 different tools in the same area for sure - with a very different feature set. docker-sync has a lot of features docker-compose does not have, going there and opening an issue with the argument "docker-sync can do this too" will not make any difference.

There is a massive different between the tool usages of docker-sync and docker-compose.

While docker-sync is run once on project start ( and that is about ). You rather ever run it again until you remake or close down the stack. So 2 or 3 times.

docker-compose is very different. You interface with the stack all the time while you working on the project, execing into a container using `docker-compose exec` or firing up and additional tool service or whatever.
The usage is very frequent thus inconvenient to be in the project root all the time.

So yet, sorry, i'am not convinced at all going with this default - but open to arguments for sure

**Comment by ostrolucky** [comment]
> There has been yet a single request to change this default - and this one is from you

Right, but from seeing issues this default caused you personally at minimum trouble with debugging the issue in https://github.com/EugenMayer/docker-sync/issues/641, because since we don't have the sane default, you cannot be sure user just didn't run docker-sync from subfolder. Furthermore, reason why people don't ask for changing default is most probably because lot of people don't know this option exists. I myself didn't know it exists only until I started digging deep into docker-sync source. Visibility of it in docs is poor. Most people just bear with current default and annoyingly always cd to parent folder.

> nor tries it to be feature complete or somewhat wrapping all this things up.

Not quite true, because docker-sync-stack does exactly that. People think of this command as pretty much alias of `docker-sync start && docker-compose up` so when that stops being true depending if you are in subfolder, that's pretty confusing. Furthermore, even when not using `docker-sync-stack`, people always run these in sequence, so if only one of them works independent if you are being in subfolder or not, that isn't good UX, is it? They have to then `cd..` solely because of docker-sync.

> While docker-sync is run once on project start ( and that is about )

I use `docker-sync logs` lot of times per day. Sometimes also `docker-sync clean` in order to attempt to correct these famous problems with synchronization.

Anyways that's fine if you don't see a big value in having this default, but could you perhaps explain why does it make more sense for `pwd` to be default? Because even if you doesn't see lot of value in having `config_path` default, I fail to see value of `pwd`.

**Comment by EugenMayer** [comment]
@ostrolucky sorry for the late answer. I understand your use case and i really also value  your arguments.

But i guess you can assume we do power-user docker-sync also, and we never had to think about this every, we neither used the option you mentioned at all. That said, since yet not a lot of people complained, i assume most of them are ok with the current default.

we are currently working on the docs in #746 to make all those little options more visible.

Also you would suggest we keep this issue open so people can start voting on this and lets see  if there are more people going into one direction.

Do not get me wrong, i'am not valueing my use case more then yours - i rather value "keep the default a lot of people use already" until we have really good reasons to not do so.

Lets search for more people seeing value in using `config_path`.

Are you ok with that?

**Comment by ostrolucky** [comment]
Thanks for coming back. Yeah. I'm not using docker-sync anymore and moved to mutagen caching that was baked into d4m in recent versions, so I'm kinda detached from this issue nowadays anyways. If people don't think this should be default, I am not going to stop anybody to close this.

**Comment by EugenMayer** [comment]
Ah nice to see that mutagen moves to d4m directly, maybe this whole mess gets cleanup up finally.

How does it perform in terms of stability and performance? if you have a second, would be nice to know. Thanks!

**Comment by ostrolucky** [comment]
Stability is 100% solved for me, no issues with that since I moved. Speed is pretty much same as it was when I was using docker-sync with osxfs

**Comment by EugenMayer** [comment]
Thanks for clarifying!

**Comment by michalkleiner** [comment]
We're using mutagen on a project now too and it's a massive difference. Near real-time performance in terms of file syncing and file-events propagation. Whatever magic it does behind the scenes — it does it well. Have mutagen project running behind the scenes for days without an issue, it has configuration options for resolution strategies, allows on-the-fly permissions tweaking, has the concept of alpha/beta sources, which can be flipped around to make the container the source for the host. Can't think of anything I would need added to it.

**Comment by EugenMayer** [comment]
@michalkleiner @ostrolucky would it make sense to integrate mutagen into docker-sync or is mutagen standalone anyway, offering all the high level bits so an integration would not make sense, rather migrating over?

**Comment by michalkleiner** [comment]
@EugenMayer as much as docker-sync helped us in past, and praise you for it — thank you! — from my perspective, mutagen.io seems more like a replacement rather than another sync strategy. No one says docker-sync can't be a wrapper for it though.

**Comment by EugenMayer** [comment]
Thank you for all the insights. If there is any successor which does all the things better and maybe ( any source @ostrolucky  ? ) is already integrated into d4m, it might be very much wort moving on and tell docker-sync users about the new option / better option.

docker-sync is here to solve an issue the best way - moving on the a project is one of the solutions, if there is a better one i'am all for it.

**Comment by ostrolucky** [comment]
https://docs.docker.com/docker-for-mac/mutagen/

**Comment by ostrolucky** [comment]
I like your approach, users could definitely be directed to this d4m+mutagen built-in approach first (maybe via readme in docker-sync?) and it could help collecting feedback. Because I am not sure it works well for everyone's use case, one common complaint I hear from mutagen users is eg CPU usage, so it might not work well if you don't have powerful machine. Another, pretty obvious thing is that this is d4m specific, so windows users are out of luck (although it's questionable how will docker-sync works in windows too). And issue tracker of mutagen is pretty full as well. Anyways we are getting way of topic here, should we create another issue where we can talk about this?

**Comment by EugenMayer** [comment]
Ok so there are drawbacks as expected, high CPU usage due to fswatch based filewatching - i was suprised how mutagen could have gone around this natural boundary for natural-fs event watching all together ( while is see the poll instead of listen concept to help here).

I think that seeing that mutagen has a lot to offer but offers one strategy only ( but this one very well ) and has a pretty cool integration, it is a good choice. But i has drawbacks and those drawbacks seem to be not only related to the strength of the hardware you are using, but also the project type ( native fs watching strongly reacts to the amount of files in the project ). So node projects might be sensible, but also php based projects tend to have a lot of files ( compared to java or golang ).

This said, i really like to still stick to the fact that docker-sync is strategy agnostic and let's you pick one for the job - and actually not just "one for the company you think fits best" - i rather talk about one for the big/long term project with specific metrix, where unison, rsync or native_osx ( OSXFS ) might shine. Be it file amount, being able to live without "sync back" or other optimizations / limitations for the specfiic sync type.

I of course would love to know what the docker-sync community thinks and how people chose what to do / what to pick, but also i think mutagen might be integrated in docker-sync being a not to far fetched idea anyway. 

I see that the whole issue here is valuable but i started it under the wrong issue all together - sorry. Kind of burried now under a far less high-level topic. I would suggest closing this one and reopening a new one to discuss the mutagen option ( in what way ever )

**Comment by EugenMayer** [comment]
closing this issue since it staled out
