### ISSUE TITLE
Looking for changes - huge node_modules

### ISSUE THREAD

**Issue by samuraitruong** [EugenMayer/docker-sync#802]
### Error
We have the very huge node_modules folder with > 400k files and multiple nested level. When I excluded node_modules, the docker-sync work perfectly, However,  I really want to include node_modules in the sync volume.

### Sync strategy
Rsync

### your docker-sync.yml
```version: "2"
options:
  verbose: true
syncs:
  platform-sync: 
    src: ./
    sync_host_ip: 'localhost'
    sync_host_port: 10872
sync_strategy: 'rsync'
sync_excludes: ['.git', 'docs']

```

### OS
MAC 12.1

**Comment by EugenMayer** [comment]
This will simply not work and there is no fix for that either. Those are the limits of OSXFS or unision we have to live with.

Pro tip: exclude node_modules and add a "copy_symbols.sh" to your repo. That one just copies over the node_module folder onces on start.sh 

Beside all that, usually copying node_modules is doomed the fail due to all the static compiled c modules in there, they wont work under the container or vice versa
