### ISSUE TITLE
Sync containers may fail to start depending on their name

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#87]
Say you have a running sync container called `project-data`, if you try to create a sync container called `project` or `data` it will fail saying that the container is already running.

**Comment by EugenMayer** [comment]
I think something is wrong in the description. You mean, you cannot name an app container like a sync container, right? Yes, this is correct and we cannot absoltely change that. If you start suffixing the container name, you will fail on docker-sync sync, since you cannot recall your old container name anymore. We would need to adjust here a lot more. Maybe all this becomes possible when we have a daemon mode or similar

**Comment by EugenMayer** [comment]
(please do not merge this for now)

**Comment by EugenMayer** [comment]
sorry, was confused, that makes total sense ( its about partial name match). I merged it, closing this issue. Thanks
